apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: fieldops-api-gateway
  namespace: fieldops-gateway
spec:
  entryPoints:
    - websecure
  tls: {}
  routes:
    # ----------------------------------------------------------------------
    # Auth Service
    # ----------------------------------------------------------------------
    - match: PathPrefix(`/api/auth`) || PathPrefix(`/api/docs`)
      kind: Rule
      middlewares:
        - name: rate-limit-auth
          namespace: fieldops-auth
        - name: security-headers
          namespace: fieldops-auth
        - name: compress
          namespace: fieldops-auth
        - name: retry-auth
          namespace: fieldops-auth
        - name: circuit-breaker-auth
          namespace: fieldops-auth
      services:
        - name: auth-service
          port: 3001
          namespace: fieldops-auth
