apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rabbitmq-management
  namespace: fieldops-data
spec:
  entryPoints:
    - websecure
  tls: {}
  routes:
    - match: Host(`rabbitmq.fieldops.local`)
      kind: Rule
      services:
        - name: rabbitmq
          port: 15672
